### PR TITLE
Dev 01

### PR DESCRIPTION
**Pull request by mjfrigaard**
> * [x] The exercises first explore markdown tables then `kable()`, but the main focus should be gtsummary

> * [x] I think it would be good to include a slide near the end about gt, maybe with the hex sticker, so I can point people to that

> * [x] I included the diabetes dataset, which I think will be good for slide examples. See the R Markdown whole game folder for a work up of this dataset that uses a couple of `gtsummary` tables

### CODE REVIEW

**Comment by malcolmbarrett** [comment]
Thanks! This is looking great. There are a few things I'd like removed and a few added if you have time this weekend. If not, please let me know so I can do it myself (speed is a bit more important here than which of us does it!)

Remove:
- The R Markdown refresher and Visual R Markdown slides (I don't think I'll ever do this deck independent of Rmd, which introduces V RMD)
- When to use tables/graphs? (I mostly teach people who need to know how to make tables not why)
- The diabetes data slide (We use this lots, so this isn't the first time they'll be seeing these data)
- Remove the R Markdown and knitr hex stickers except for the `knitr::kable()` slide, and make the image a little bigger on that slide. (It's just inconsistent with how I normally do it.)
- For the gtsummary slides, just show the hex on the first slide
- Remove some of the focus on `kable()` output types, as it's generally better to let knitr decide. The `pipe` format might be useful for a slide to show what's happening. I also think you should show the table output itself (with the exception of maybe the pipe slide), not the underlying structure
- Remove the `Check with attr()` part of the labelled slides

Add/modify:
- The your turn exercises, which should be interspersed throughout as appropriate. 
- Also, make sure you are teaching to those. Right now, the following your turns don't have matching content: **Your Turn 1**, **Your Turn 3**, **Your Turn 6**. You don't need to cover everything for those, but that basically means adding a slide on 1) markdown tables/tables with Visual Rmd 2) `tbl_cross()` and 3) cross-referencing tables (which means connecting that idea to `modify_caption()` and using `\@ref(tab:name-of-chunk)`. 
- An example of making labels using the `list()` style (which is what I tend to use; put that first, but keep your slides on the labelled package, as the idea is helpful)
- I don't like the name `d2`. Can we call it `table_data` or something? I feel similarly about `d3`
- Please run styler on the code chunks

**Comment by malcolmbarrett** [comment]
For cross-referencing, this simple structure might be useful: https://github.com/malcolmbarrett/r_teaching_warehouse/blob/0ad4c30871f2968e0f3568c6be38ca78d5d451fa/rmarkdown_figures/rmarkdown_figures.Rmd#L541-L568. The complex thing is that captions are created in different ways depending on what you use, e.g. `caption` in `kable()` or `modify_caption()` in gtsummary.

**Comment by mjfrigaard** [comment]
Thank you for getting back to me to quick--I can get these revisions made and back to you later today/tomorrow morning. And thank you for the ref on cross-referencing figures! I love it when I encounter this in someone else's materials, so I definitely need to learn how to do it myself!

**Comment by malcolmbarrett** [comment]
Awesome, thanks for your hard work on this!

**Pull request closed without merging**
